USE MASTER;
IF EXISTS(SELECT 1 FROM sys.databases WHERE name='DWBI')
BEGIN
	ALTER DATABASE DWBI SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE DWBI;
END;
GO
CREATE DATABASE DWBI;

USE DWBI;

CREATE SCHEMA dim;
GO
CREATE SCHEMA fact;
GO
CREATE SCHEMA stage;
GO